---
- name: create ipython config folder
  file:
    path: "${HOME}/.ipython/profile_default"
    state: directory

- name: setup AiiDA jupyter extension
  copy:
    src: ipython_config.py
    dest: "${HOME}/.ipython/profile_default"

- name: create aiidalab folders
  become: True
  become_user: "{{ root_user }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ current_user }}"
  with_items:
    - "{{ aiidalab_base_folder }}"
    - "{{ aiidalab_apps_folder }}"

- name: touch __init__.py for import
  become: True
  become_user: "{{ root_user }}"
  file:
    path: "{{ aiidalab_apps_folder }}/__init__.py"
    state: touch

- name: add launcher script
  template:
    src: start.sh
    dest: "{{ aiidalab_apps_folder }}"
    mode: 0753

- name: update PYTHONPATH
  lineinfile:
    path: "${HOME}/.profile"
    line: 'export PYTHONPATH=$PYTHONPATH:{{ aiidalab_base_folder }}'

- name: create aiidalab apps symlink
  file:
    src: "{{ aiidalab_apps_folder }}"
    dest: "{{ aiidalab_apps_symlink }}"
    state: link

- name: create desktop shortcut
  template:
    src: apps.desktop
    dest: "${HOME}/Desktop"
    mode: 0753
  when: not aiidalab_headless

# below: stuff needed for jupyterhub
#- name: copy singleuser script
#  copy:
#    src: mc-jupyter-singleuser
#    dest: "{{ aiida_venv }}/bin"
#    mode: u+x

#- name: start jupyter notebook server
#  shell: |
#    {{ aiida_venv }}/bin/mc-jupyterhub-singleuser \
#    --ip=0.0.0.0  \
#    --port=8888   \
#    --notebook-dir="{{ aiidalab_apps_folder }}" \
#    --NotebookApp.iopub_data_rate_limit=1000000000 \
#    --NotebookApp.default_url="/apps/home/start.ipynb"
